/**
 * Legal caption rendering regression.
 *
 * Bankruptcy "Certificate of Service" documents put the debtor, case number and
 * chapter in a single caption paragraph driven by ONE left tab stop (5039 twips),
 * a hanging indent and a right indent. Faithful viewers (Word / Google Docs /
 * Pages) tab the case number to the 5039 stop and wrap the hyphenated case number
 * at the dash:
 *
 *     In re:
 *     JANE ALEXANDRA DOE,            Case No. 00-00000-
 *         MAM Debtor.               Chapter 13
 *     ____________________________/
 *
 * A regression in tab-stop origin or hyphen line-breaking (the bug fixed in commit
 * 54aa655) instead FORCES the case number flush to the right margin and keeps
 * "…00-00000-MAM" on one line. This test loads the sanitized `legal-caption.docx`
 * fixture and asserts the faithful layout against the VISIBLE painted pages
 * (layout-painter output under `.paged-editor__pages`, not the hidden ProseMirror).
 *
 * Fixture: e2e/fixtures/legal-caption.docx (generated by generate-fixtures.ts).
 */
import { test, expect, type Page } from '@playwright/test';
import { EditorPage } from '../helpers/editor-page';

const FIXTURE = 'fixtures/legal-caption.docx';

interface Fragment {
  text: string;
  top: number;
  left: number;
  right: number;
}

/**
 * Collect painted text fragments from the VISIBLE pages only. The hidden
 * ProseMirror is rendered off-screen (left: -9999px) and must be excluded, so we
 * scope the walk to `.paged-editor__pages`.
 */
async function collectVisibleFragments(page: Page): Promise<Fragment[]> {
  return page.evaluate(() => {
    const root = document.querySelector('.paged-editor__pages');
    if (!root) return [];
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, null);
    const frags: Array<{ text: string; top: number; left: number; right: number }> = [];
    let node: Node | null;
    while ((node = walker.nextNode())) {
      const text = (node.textContent || '').replace(/\s+/g, ' ').trim();
      if (!text) continue;
      const range = document.createRange();
      range.selectNodeContents(node);
      const r = range.getBoundingClientRect();
      if (r.width === 0 && r.height === 0) continue;
      frags.push({
        text,
        top: Math.round(r.top),
        left: Math.round(r.left),
        right: Math.round(r.right),
      });
    }
    frags.sort((a, b) => a.top - b.top || a.left - b.left);
    return frags;
  });
}

test.describe('Legal caption rendering', () => {
  test('faithfully tabs and wraps a bankruptcy caption (no forced right margin)', async ({
    page,
  }) => {
    const editor = new EditorPage(page);
    await editor.goto();
    await editor.waitForReady();

    await editor.loadDocxFile(FIXTURE);

    // Wait until the painted caption is on screen.
    await page.waitForFunction(
      () => {
        const root = document.querySelector('.paged-editor__pages');
        const t = root?.textContent ?? '';
        return t.includes('Case No.') && t.includes('Chapter 13') && t.includes('Debtor');
      },
      { timeout: 10000 }
    );
    await page.waitForTimeout(300); // let fonts/layout settle

    const frags = await collectVisibleFragments(page);

    const name = frags.find((f) => f.text.includes('JANE ALEXANDRA DOE'));
    const caseNo = frags.find((f) => f.text.startsWith('Case No.'));
    const mam = frags.find((f) => f.text.startsWith('MAM'));
    const chapter = frags.find((f) => f.text.includes('Chapter 13'));

    // Faithful rendering means every caption piece is painted (nothing dropped).
    expect(name, 'debtor name painted').toBeTruthy();
    expect(caseNo, 'case number painted').toBeTruthy();
    expect(mam, 'MAM/Debtor painted').toBeTruthy();
    expect(chapter, 'Chapter 13 painted').toBeTruthy();
    if (!name || !caseNo || !mam || !chapter) return;

    // 1. The case number tabs in to the document's stop and shares the name's line
    //    (it is not pushed onto its own line).
    expect(Math.abs(caseNo.top - name.top), 'case number on the name line').toBeLessThanOrEqual(6);
    expect(caseNo.left, 'case number is tabbed in, not at the left margin').toBeGreaterThan(
      name.left + 100
    );

    // 2. NOT forced to the right margin: the case number column aligns with the
    //    "Chapter 13" column — both land on the single 5039-twip tab stop. Under
    //    the regression the case number was flush to the right margin instead.
    expect(
      Math.abs(caseNo.left - chapter.left),
      'case number aligns to the same tab stop as Chapter 13 (not the right margin)'
    ).toBeLessThanOrEqual(12);

    // 3. Faithful hyphen wrap: line 1 ends at the dash ("…00-00000-") and
    //    "MAM Debtor." flows to the next line. The regression kept the whole
    //    "…00-00000-MAM" token on line 1.
    expect(caseNo.text, 'case number wraps at the hyphen').not.toContain('MAM');
    expect(caseNo.text.endsWith('-'), 'line 1 ends at the hyphen').toBe(true);
    expect(mam.top, '"MAM Debtor." wraps below the case-number line').toBeGreaterThan(
      caseNo.top + 10
    );
    expect(
      Math.abs(chapter.top - mam.top),
      'Chapter 13 sits on the wrapped line'
    ).toBeLessThanOrEqual(6);

    // 4. The wrapped line indents to the paragraph's 0.5" left indent — to the
    //    right of the margin but to the left of the tab-stop column.
    expect(mam.left, 'wrapped line indented past the margin').toBeGreaterThan(name.left);
    expect(mam.left, 'wrapped line sits left of the tab-stop column').toBeLessThan(caseNo.left);
  });
});
